services:
axelor:
image: axelor/app-base-image
restart: always
ports:
- 8086:80
volumes:
- test_postgresql_app:/var/lib/postgresql
- test_postgresql_log:/var/log/postgresql
- test_tomcat_webapp:/var/lib/tomcat
- test_tomcat_log:/var/log/tomcat

volumes:
test_postgresql_app:
test_postgresql_log:
test_tomcat_webapp:
test_tomcat_log:
